import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col">
        <header className="border-b-1 border-gray-600 px-4 py-2 bg-gray-900">
          <h1 className="text-lg">Motif</h1>
        </header>
        <div className="flex grow flex-col bg-gray-900">{children}</div>
        <footer className="border-t-1 border-gray-600 px-4 py-2 bg-gray-900">
          Built by Zach Coursey
        </footer>
      </body>
    </html>
  );
}
